### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by tbergq** [superlaziness/t9js#1]
Hi 👋 how are you?

I noticed that there are no tests, could you please add some?

**Comment by superlaziness** [comment]
Hello! I’m fine, and you? 
Sure, I’ll add tests on the weekend. Is it ok?

**Comment by tbergq** [comment]
Hi, I am fine thank you. 

Yes you can add it during the weekend. Just ping me when it is done 🙂

**Comment by superlaziness** [comment]
Roger that!

**Comment by superlaziness** [comment]
@tbergq 🏓

**Comment by tbergq** [comment]
Thanks, I will have look at it now 👍
